### PR TITLE
Change nethash to optional - Closes #646

### LINKED ISSUE #646: APIClient does not require detailed information
### Description

APIClient used to require a lot of information, such as
- nethash
- version
- minVersion

However, none of those header information are required in the 1.0.0 version

### Steps to Reproduce
Call any 1.x.x API endpoint through browser.

### Versions
1.0.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Although nethash was not required from `core` API, it was required in the APIClient.

### How did I fix it?
Remove `nethash` from required constructor input, and read it from optional field.

### How to test it?
```
const client = elements.APIClient(['http://localhost:4000']);
client.node.getConstants().then(console.log);
```

### Review checklist

* The PR solves #646
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: src/api_client/api_client.js [hunk 1]
```diff
@@ -69,29 +59,36 @@ export default class APIClient {
 	}
 
 	static createMainnetAPIClient(options) {
-		return new APIClient(MAINNET_NODES, MAINNET_NETHASH, options);
+		return new APIClient(
+			MAINNET_NODES,
+			Object.assign({}, options, { nethash: MAINNET_NETHASH }),
```
Comment (willclarktech) [inline src/api_client/api_client.js]: Is this definitely the right order? Could there be a use case where somebody wants to use this with a custom nethash? (In which case `Object.assign({}, { nethash: MAINNET_NETHASH }, options)` would be better.)

File: src/api_client/api_client.js [hunk 2]
```diff
@@ -69,29 +59,36 @@ export default class APIClient {
...
-		if (typeof nethash !== 'string' || nethash === '') {
-			throw new Error('APIClient requires nethash for initialization.');
-		}
-
 		const options = Object.assign({}, defaultOptions, providedOptions);
 
-		this.headers = getHeaders(nethash, options.version, options.minVersion);
+		this.headers = options.nethash
+			? Object.assign({}, commonHeaders, { nethash: options.nethash })
+			: commonHeaders;
```
Comment (willclarktech) [inline src/api_client/api_client.js]: We should have a fresh object here in case people override `myClientInstance.headers` and don't expect it to affect other clients.

File: src/api_client/api_client.js [hunk 3]
```diff
@@ -69,29 +59,36 @@ export default class APIClient {
...
+		);
 	}
 
-	initialize(nodes, nethash, providedOptions = {}) {
+	initialize(nodes, providedOptions = {}) {
 		if (!Array.isArray(nodes) || nodes.length <= 0) {
 			throw new Error('APIClient requires nodes for initialization.');
 		}
 
-		if (typeof nethash !== 'string' || nethash === '') {
```
Comment (willclarktech) [inline src/api_client/api_client.js]: We might still want a minimal check like this even if it's provided in options. E.g. somebody passes an array...

File: test/api_client/api_client.js [hunk 4]
```diff
@@ -38,18 +38,11 @@ describe('APIClient module', () => {
 	];
 	const defaultHeaders = {
 		'Content-Type': 'application/json',
-		nethash: mainnetHash,
-		os: 'lisk-js-api',
```
Comment (willclarktech) [inline test/api_client/api_client.js]: This might be useful for analytics.

Comment (slaweet) [reply test/api_client/api_client.js]: Yes, I was thinking about analytics recently and this might be very useful.

File: src/api_client/api_client.js [hunk 5]
```diff
@@ -84,11 +85,17 @@ export default class APIClient {
 			throw new Error('APIClient requires nodes for initialization.');
 		}
 
+		if (typeof providedOptions !== 'object' || Array.isArray(providedOptions)) {
+			throw new Error(
+				'APIClient requires the second parameter to be an object.',
```
Comment (willclarktech) [inline src/api_client/api_client.js]: We should make clear that it's optional. E.g. `APIClient takes an optional object as the second parameter.`?
