### PR TITLE
Fix tests for the browser - Closes #550

### LINKED ISSUE #550: Fix browser tests 0.5.1
**Expected behavior**

Browsertest should pass

**Current behaviour**

Browsertests do not pass

**Setup**

Branch 0.5.0 and therefore affecting 0.5.1, the browsertest fail.

**Possible Fix**

Browsertest need to be updated with sinon, slots module and various timeouts.

### PR DESCRIPTION
**Pull request by Tosch110**
For branch 0.5.1
Closes #550

### CODE REVIEW

File: test/api/liskApi.js [hunk 1]
```diff
@@ -896,14 +903,7 @@ describe('Lisk.api()', function () {
 	describe('#checkReDial', function () {
 
 		it('should check if all the peers are already banned', function () {
-			(lisk.api().checkReDial()).should.be.equal(true);
-		});
-
-		it('should be able to get a new node when current one is not reachable', function (done) {
```
Comment (willclarktech) [inline test/api/liskApi.js]: Why is this test removed?

Comment (Tosch110) [reply test/api/liskApi.js]: Because it duplicates this test: https://github.com/LiskHQ/lisk-js/pull/548/files#diff-03dab7dc7afe96c8322cab28bdf86f72R940
